# Generated by Django 5.2 on 2025-05-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language1', models.CharField(max_length=20)),
                ('language2', models.CharField(max_length=20)),
                ('language3', models.CharField(max_length=20)),
                ('language4', models.CharField(max_length=20)),
                ('language5', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='About_Me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Experience', models.CharField(max_length=20)),
                ('Country', models.CharField(max_length=10)),
                ('Age', models.CharField(max_length=3)),
                ('Favorite_language', models.CharField(max_length=10)),
                ('Degree', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNumber', models.CharField(max_length=11)),
                ('Location', models.TextField()),
                ('Email', models.EmailField(max_length=100)),
                ('Website', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('Email', models.EmailField(max_length=100)),
                ('Body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Social_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Github', models.CharField(max_length=70)),
                ('Instagram', models.CharField(max_length=70)),
                ('Telegram', models.CharField(max_length=70)),
            ],
        ),
    ]
